import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>

    
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Each time you visit a different URL, Next.js figures out the matching page.js file, and then injects it into {children} in your layout — automatically. */}
        <Provider>
        {children}
          </Provider>  
               {/* This ensures that any child component inside {children} — which is any page or nested layout — can access the user data via Context.You don’t need to manually pass props to every child component.



 */}
            <Toaster/>
      </body>
    </html>

    </ClerkProvider>



  );
}
